/**
 * OPA (Open Policy Agent) client for the agentspec sidecar.
 *
 * This module implements Layer 2 of the OPA integration:
 *   1. buildOPAInput  — assembles the OPA `input` document from manifest + probe data
 *   2. queryOPA       — POSTs the input to OPA and returns allow/deny decision
 *
 * OPA is expected to run as a sidecar container at OPA_URL (default: http://localhost:8181).
 * If OPA is unavailable the sidecar falls back gracefully — no violations, allow=true.
 * This ensures OPA is additive; removing or restarting OPA never breaks the gap endpoint.
 *
 * OPA query endpoint:
 *   POST /v1/data/agentspec/agent/<agent_name>/deny
 *   Body: { input: OPAInput }
 *   Response: { result: string[] }  — the set of deny rule IDs that fired
 *
 * Deny rule IDs correspond to rules generated by `agentspec generate-policy`:
 *   "pii_detector_not_invoked", "toxicity_threshold_exceeded", ...
 */

import type { AgentSpecManifest, HealthReport } from '@agentspec/sdk'
import type { AgentProbeResult } from './agent-probe.js'

// ── Public types ───────────────────────────────────────────────────────────────

/**
 * The OPA input document sent with each query.
 *
 * In a full implementation, the framework sub-SDK (sdk-langgraph, sdk-crewai, …)
 * would populate fields like `guardrails_invoked`, `toxicity_score`, and
 * `tools_called` from live runtime events. For the sidecar's gap analysis,
 * we populate what we can from the manifest + probe, and leave runtime-only
 * fields at their zero values.
 */
export interface OPAInput {
  /** Agent name from metadata.name */
  agent_name: string
  /** Always "llm_call" for gap analysis queries */
  request_type: 'llm_call' | 'tool_call' | 'memory_write'
  /** Model identifier as "provider/id" */
  model_id: string
  /** Guardrail types declared in agent.yaml */
  guardrails_declared: string[]
  /**
   * Guardrail types actually invoked on this request.
   * Set by the framework sub-SDK from runtime events.
   * For sidecar gap analysis: empty (worst-case assumption).
   */
  guardrails_invoked: string[]
  /** Tool names registered in the agent (from probe or /capabilities) */
  tools_registered: string[]
  /** Whether the agent has integrated @agentspec/sdk (AgentSpecReporter) */
  sdk_available: boolean
  /** Whether the agent exposes GET /health */
  has_health_endpoint: boolean
  /** Whether the agent exposes GET /capabilities */
  has_capabilities_endpoint: boolean
  /** Whether all probe checks are passing */
  all_checks_passing: boolean

  // ── Runtime fields (populated by framework sub-SDKs, not sidecar) ──────────
  /** Tool names called in this request (populated by sdk-langgraph, etc.) */
  tools_called?: string[]
  /** Whether the user explicitly confirmed before destructive tool execution */
  user_confirmed?: boolean
  /** Toxicity score of model output (0.0–1.0) */
  toxicity_score?: number
  /** Hallucination score of model output (0.0–1.0) */
  hallucination_score?: number
  /** Memory write event — TTL and PII scrub status */
  memory_write?: { ttl_seconds: number; pii_scrubbed: boolean }
  /** Cumulative cost in USD for today */
  cost_today_usd?: number
  /** Cumulative token count for today */
  tokens_today?: number
}

export interface OPAResult {
  /** true if no deny rules fired (or OPA unavailable) */
  allow: boolean
  /** Deny rule IDs that fired (empty when allow=true or OPA unavailable) */
  violations: string[]
  /**
   * true when OPA was not reachable.
   * Callers can use this to add an informational gap note.
   */
  opaUnavailable?: boolean
}

// ── Input builder ──────────────────────────────────────────────────────────────

/**
 * Parse a comma-separated header value into an array of trimmed strings.
 * Handles both string and string[] header shapes from Fastify.
 *
 *   "pii-detector, toxicity-filter" → ["pii-detector", "toxicity-filter"]
 *   undefined                       → []
 */
export function parseCommaSeparatedHeader(
  value: string | string[] | undefined,
): string[] {
  if (!value) return []
  // HTTP allows multiple header instances; join all values before splitting on commas
  const raw = Array.isArray(value) ? value.join(',') : value
  if (!raw.trim()) return []
  return raw
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
}

/**
 * Build an OPAInput from real behavioral data reported by the agent.
 *
 * This is used by two reporting paths:
 *   - HeaderReporting: sidecar reads X-AgentSpec-* response headers set by the agent
 *   - EventPush: POST /agentspec/events pushes behavioral data out-of-band
 *
 * Unlike the old honor-system approach (reading client REQUEST headers),
 * this data comes from the agent's execution path via the sdk-langgraph sub-SDK.
 */
export function buildBehavioralOPAInput(
  manifest: AgentSpecManifest,
  guardrailsInvoked: string[],
  toolsCalled: string[],
  userConfirmed?: boolean,
): OPAInput {
  const spec = manifest.spec

  const input: OPAInput = {
    agent_name: manifest.metadata.name,
    request_type: 'llm_call',
    model_id: `${spec.model.provider}/${spec.model.id}`,
    guardrails_declared: (spec.guardrails?.input ?? []).map((g) => g.type),
    guardrails_invoked: guardrailsInvoked,
    tools_registered: (spec.tools ?? []).map((t) => t.name),
    sdk_available: false,
    has_health_endpoint: false,
    has_capabilities_endpoint: false,
    all_checks_passing: false,
  }

  if (toolsCalled.length > 0) input.tools_called = toolsCalled
  if (userConfirmed) input.user_confirmed = true

  return input
}

/**
 * Assemble an OPAInput from the manifest, probe result, and observed endpoints.
 *
 * This is a pure function — no I/O. The sidecar calls this before querying OPA.
 */
export function buildOPAInput(
  manifest: AgentSpecManifest,
  probe: AgentProbeResult,
  observed: { hasHealth: boolean; hasCapabilities: boolean; tools: string[] },
): OPAInput {
  const spec = manifest.spec

  // Declared input guardrail types
  const guardrailsDeclared = (spec.guardrails?.input ?? []).map((g) => g.type)

  // Registered tools: from probe checks (tool:*) when SDK available, else from /capabilities
  let toolsRegistered: string[]
  if (probe.sdkAvailable && probe.report) {
    toolsRegistered = probe.report.checks
      .filter((c) => c.category === 'tool')
      .map((c) => c.id.replace(/^tool:/, ''))
  } else {
    toolsRegistered = observed.tools
  }

  // Check whether all probe checks are passing
  let allChecksPassing = false
  if (probe.sdkAvailable && probe.report) {
    allChecksPassing = probe.report.checks.every((c) => c.status === 'pass')
  }

  return {
    agent_name: manifest.metadata.name,
    request_type: 'llm_call',
    model_id: `${spec.model.provider}/${spec.model.id}`,
    guardrails_declared: guardrailsDeclared,
    guardrails_invoked: [], // Runtime-only — populated by framework sub-SDK
    tools_registered: toolsRegistered,
    sdk_available: probe.sdkAvailable,
    has_health_endpoint: observed.hasHealth,
    has_capabilities_endpoint: observed.hasCapabilities,
    all_checks_passing: allChecksPassing,
  }
}

// ── OPA HTTP client ────────────────────────────────────────────────────────────

/**
 * Sanitize an agent name for use in the OPA query path.
 *
 * Rego package identifiers cannot contain hyphens — they must be replaced
 * with underscores to match the package name generated by `agentspec generate-policy`.
 *
 * Throws if the resulting identifier contains path-traversal characters or
 * does not match the allowed character set (mirrors the Python SDK validation).
 *
 * Example: "fitness-tracker" → "fitness_tracker"
 *   → POST /v1/data/agentspec/agent/fitness_tracker/deny
 */
function sanitizeAgentName(name: string): string {
  const sanitized = name.replace(/-/g, '_')
  if (!/^[a-z][a-z0-9_]{0,63}$/.test(sanitized)) {
    throw new Error(
      `Invalid agent name for OPA query: "${name}". ` +
        'Must start with a lowercase letter, contain only lowercase alphanumeric ' +
        'characters, hyphens, or underscores, and be at most 64 characters.',
    )
  }
  return sanitized
}

/**
 * Query the OPA deny rule set for this agent.
 *
 * Returns allow=true (no violations) if OPA is unreachable — fail-open
 * for the gap endpoint (OPA is additive, never blocking).
 *
 * @param opaBaseUrl  e.g. "http://localhost:8181"
 * @param agentName   e.g. "gymcoach" or "fitness-tracker"
 * @param input       The OPAInput document to evaluate
 */
export async function queryOPA(
  opaBaseUrl: string,
  agentName: string,
  input: OPAInput,
): Promise<OPAResult> {
  const sanitized = sanitizeAgentName(agentName)
  const url = `${opaBaseUrl}/v1/data/agentspec/agent/${sanitized}/deny`

  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ input }),
      signal: AbortSignal.timeout(3_000), // OPA must respond within 3 s
    })

    if (!res.ok) {
      return { allow: true, violations: [], opaUnavailable: true }
    }

    const body = (await res.json()) as { result?: unknown }
    const result = body.result

    // OPA returns the deny set as an array of strings.
    // If the policy hasn't been loaded yet, result is null/undefined.
    if (!Array.isArray(result) || result.length === 0) {
      return { allow: true, violations: [] }
    }

    // Filter to string violations only (defensive — should always be strings)
    const violations = result.filter((v): v is string => typeof v === 'string')
    return {
      allow: violations.length === 0,
      violations,
    }
  } catch {
    // ECONNREFUSED, timeout, parse error — OPA not available, fail-open
    return { allow: true, violations: [], opaUnavailable: true }
  }
}

// ── Gap issue converter ────────────────────────────────────────────────────────

/**
 * Convert OPA violation IDs to GapIssue objects compatible with the gap report.
 *
 * Violation IDs are Rego rule names like "pii_detector_not_invoked".
 * We convert underscores back to readable text for the issue description.
 */
export function opaViolationsToGapIssues(
  violations: string[],
): Array<{
  severity: 'critical' | 'high' | 'medium' | 'low'
  property: string
  description: string
  recommendation: string
  evidenceLevel: 'behavioral'
}> {
  return violations.map((id) => {
    const description = id.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
    return {
      severity: severityForViolation(id),
      property: `opa:${id}`,
      description: `OPA policy violation: ${description}`,
      recommendation: opaRemediation(id),
      evidenceLevel: 'behavioral' as const,
    }
  })
}

function severityForViolation(
  id: string,
): 'critical' | 'high' | 'medium' | 'low' {
  if (id.includes('cost') || id.includes('destructive')) return 'critical'
  if (id.includes('pii') || id.includes('injection') || id.includes('ttl')) return 'high'
  if (id.includes('toxicity') || id.includes('hallucination')) return 'medium'
  return 'low'
}

function opaRemediation(id: string): string {
  const remediations: Record<string, string> = {
    pii_detector_not_invoked:
      'Ensure the pii-detector guardrail is invoked before every LLM call. Use @agentspec/sdk-langgraph AgentSpecToolNode to auto-invoke guardrails.',
    topic_filter_not_invoked:
      'Ensure the topic-filter guardrail runs on every input. Register it in your guardrail middleware.',
    prompt_injection_not_invoked:
      'Invoke the prompt-injection guardrail on every user message before forwarding to the LLM.',
    toxicity_threshold_exceeded:
      'The model output exceeded the declared toxicity threshold. Add output filtering or reduce the threshold.',
    hallucination_threshold_exceeded:
      'The model output exceeded the hallucination threshold. Enable retrieval-augmented generation or increase context.',
    monthly_cost_limit_exceeded:
      'Token spend is on track to exceed the declared maxMonthlyUSD limit. Add token budgeting to your agent.',
    memory_ttl_mismatch:
      'Memory writes are not using the declared TTL. Ensure RedisSaver is configured with the correct TTL from the manifest.',
    destructive_tool_without_confirmation:
      'A destructive tool was called without user confirmation. Add a human-in-the-loop approval step before destructive operations.',
  }
  return remediations[id] ?? `Review and remediate OPA policy violation: ${id}`
}
